legacy_layout=false

background_alpha=0
round_corners=10
background_color=000000

font_size=20
text_color=FFFFFF
position=top-left

table_columns=4
width=220
offset_x=5
offset_y=5

toggle_hud=F12
toggle_fps_limit=Shift_L+F1
toggle_logging=Shift_L+F2
toggle_preset=Super_L+G

preset=1,2

gl_vsync=0
vsync=0
vulkan_present_mode=immediate

fps_limit=0

text_outline
text_outline_thickness=1.3
hud_no_margin
hud_compact
