[Audio]
Volume=100

[General]
FooterStyle=floating
FullscreenOnStartUp=true
LastPlayedFile=file:///run/media/caue/wd_240/5jun/GX010421.MP4
LastUrl=https://www.instagram.com/tv/CRhcgNqgAmI/?utm_source=ig_web_copy_link&igsi=MzRlODBiNWFlZA==
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true

[Mouse]
Back=playPreviousAction
Forward=playNextAction
ScrollDown=seekBackwardSmallAction
ScrollUp=seekForwardSmallAction

[Playback]
HWDecoding=vaapi
